on: push
name: Deploy on Now
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: deploy
      uses: actions/zeit-now@master
      env:
        ZEIT_TOKEN: ${{ secrets.ZEIT_TOKEN }}
      with:
        args: --public --no-clipboard deploy ./site > $HOME/${{ github.action }}.txt
   
